<a href="https://colab.research.google.com/github/ANNON17-byte/pytorch/blob/main/tensors_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [3]:
if torch.cuda.is_available():
  print(f"GPU availab : {torch.cuda.get_device_name(0)}")

else :
  print("GPU not availab")

GPU availab : Tesla T4


# CREATING **TENSORS**

In [5]:
#using empty
a = torch.empty(2,3)
print(a)

tensor([[2.1715e-18, 2.3081e-12, 2.6302e+20],
        [6.1943e-04, 3.6022e-12, 6.9989e+22]])


In [6]:
#check type
type(a)

torch.Tensor

In [8]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])