<a href="https://colab.research.google.com/github/ANNON17-byte/pytorch/blob/main/tensors_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [3]:
if torch.cuda.is_available():
  print(f"GPU availab : {torch.cuda.get_device_name(0)}")

else :
  print("GPU not availab")

GPU availab : Tesla T4


# CREATING **TENSORS**

In [5]:
#using empty
a = torch.empty(2,3)
print(a)

tensor([[2.1715e-18, 2.3081e-12, 2.6302e+20],
        [6.1943e-04, 3.6022e-12, 6.9989e+22]])


In [6]:
#check type
type(a)

torch.Tensor

In [8]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
#using rand
torch.rand(2,3)

tensor([[0.3400, 0.1239, 0.9084],
        [0.5915, 0.3220, 0.5350]])

In [11]:
#using seed
torch.manual_seed(100) #it will generate the exact same "random" numbers every single time you run it.
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [6]:
#using tensor
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
#other ways

#arange
print("arange: " , torch.arange(0,10))

#linspace
print("linspace: ", torch.linspace(0,10,2))

#eye
print("eye: ", torch.eye(5))

#full
print("full: ", torch.full((3,3),5))

arange:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
linspace:  tensor([ 0., 10.])
eye:  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
full:  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Sapes


In [9]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
x.shape

torch.Size([2, 3])

In [11]:
torch.empty_like(x) #function creates a new tensor with the exact same shape and data type as your existing tensor x

tensor([[0, 0, 0],
        [0, 0, 0]])

In [12]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [13]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [14]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.7701, 0.5712, 0.3196],
        [0.6653, 0.6671, 0.7119]])

# Tensor Data Types

In [15]:
x.dtype

torch.int64

In [16]:
torch.tensor([1.0,2.0], dtype = torch.int32)

tensor([1, 2], dtype=torch.int32)

In [17]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [18]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations

In [19]:
x = torch.rand(2,2)
x

tensor([[0.8744, 0.9332],
        [0.8646, 0.4263]])

In [20]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.7646, 0.8708],
        [0.7475, 0.1817]])

# Element wise operation

In [21]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.5800, 0.6036, 0.6370],
        [0.6833, 0.0434, 0.3247]])
tensor([[0.2992, 0.3676, 0.3124],
        [0.4544, 0.0017, 0.8231]])


In [22]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.2808, 0.2360, 0.0122],
        [0.2289, 0.0005, 0.3247]])

In [24]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [25]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [26]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [27]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [28]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [29]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [30]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [31]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# Reduction operation

In [32]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[0., 3., 7.],
        [1., 7., 9.]])

In [35]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([10., 17.])

In [36]:

# sum along rows
torch.sum(e, dim=1)

tensor([10., 17.])

In [37]:
# median
torch.median(e)

tensor(3.)

# Matrix operations

In [38]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[2, 1, 5],
        [4, 1, 5]])
tensor([[9, 6],
        [5, 2],
        [6, 8]])


In [39]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[53, 54],
        [71, 66]])

In [40]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [44]:
# transpose
torch.transpose(f, 1,0)

tensor([[2, 4],
        [1, 1],
        [5, 5]])

# Comparison operations

In [45]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[1, 4, 5],
        [2, 5, 1]])
tensor([[0, 7, 8],
        [7, 6, 9]])


In [46]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

# Special functions

In [47]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[7., 6., 6.],
        [0., 8., 7.]])

In [48]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.9975, 0.9975],
        [0.5000, 0.9997, 0.9991]])

In [49]:
# relu
torch.relu(k)

tensor([[7., 6., 6.],
        [0., 8., 7.]])

In [50]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.9909e-01, 1.1920e-01, 2.6894e-01],
        [9.1105e-04, 8.8080e-01, 7.3106e-01]])

# Inplace Operations

In [51]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.3273, 0.3598, 0.1152],
        [0.7883, 0.9127, 0.5112]])
tensor([[0.3103, 0.1664, 0.8711],
        [0.4704, 0.2635, 0.6892]])


In [52]:
m.relu_()

tensor([[0.3273, 0.3598, 0.1152],
        [0.7883, 0.9127, 0.5112]])

# Copying a Tensor

In [53]:
a = torch.rand(2,3)
a

tensor([[0.0401, 0.0932, 0.9629],
        [0.6252, 0.2398, 0.8977]])

In [54]:
b = a
b

tensor([[0.0401, 0.0932, 0.9629],
        [0.6252, 0.2398, 0.8977]])

In [55]:
id(a)

132977003375552